# Generated by Django 5.2.3 on 2026-04-07 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0002_student_company_name_student_package_lpa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='cgpa',
        ),
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
    ]
